### PR TITLE
CI: Maintenance (updated actions, speedups)

### PR DESCRIPTION
**Pull request by EwoutH**
- Run on Pull Requests
 - Updates [actions/checkout](https://github.com/actions/checkout) to v2 (which does a shallow clone by default for a speedup)
 - Uses [actions-rs/toolchain](https://github.com/actions-rs/toolchain) for toolchain installation
 - Uses [actions-rs/clippy-check](https://github.com/actions-rs/clippy-check) for lint job (which has tight integration with GitHub)

There are also two issues at this moment that should be addressed:
The _Code Formatting_ job seems to do nothing

### CODE REVIEW

**Comment by jim-signal** [comment]
Hi @EwoutH, we will soon publish a new version of RingRTC which already fixes some of these things, including the v2. The clippy changes here were temporary, and we have fixed those to use the latest version of the compiler. If you still see some needed changes, please rebase off of the latest (when published, hopefully in the next day or two, v2.9.0). Thanks!

**Comment by EwoutH** [comment]
Wow that's a quick response, thanks! I will check it out as when it's released.

I must say that your development model with private repos is a bit inconvenient for outside contributors. Comma.ai used to also to it this way, but they switched to a fully public model last year! [A 2020 Theme: Externalization](https://medium.com/@comma_ai/a-2020-theme-externalization-13b33326d8b3))

**Comment by EwoutH** [comment]
I rebased this PR and resolved conflicts. It now mainly switches installing Rust to the [actions-rs/toolchain](https://github.com/actions-rs/toolchain) action, which I still think is a useful change since it will be maintained to keep installing Rust correctly.

**Comment by jim-signal** [comment]
Hi @EwoutH, this also looks good, we will merge it in. Thanks!

**Pull request merged**
